src/index.ts
> Identity map
> Make optional values for rights invocations optional
=> fix(types): id map + optional

src/index.ts
=> fix(experience): experienceDefault

src/index.ts
> Update names for jurisdiction, property, environment
=> fix(naming): jurisdiction + property

src/index.ts
=> fix(theme) update to v2

src/index.ts
=> fix(theme) update data model

src/index.ts, test/index.test.ts
> Take base url param that will be set using config services
=> fix(baseUrl): take base url param

src/index.ts
=> fix(purpose): add tcf

src/index.ts
=> fix(config): update vendor model

src/index.ts
Align with supercargo config.json key for `tcfID` (instead of `tcfId`)
To be tested in DEV
N/A
=> chore(casing): update casing in Purpose

src/index.ts
Add fields to vendor model for use downstream
To be tested in DEV
N/A
=> fix(vendor-model): add fields to vendor model

src/index.ts
=> fix(canonicalPurpose): add canonical purpose

src/index.ts
Split out canonicalPurposes
Add legal basis metadata
=> fix(config): canonPurp split + lb metadata

src/index.ts
=> fix(config): add vendor storage

src/index.ts
Accidentally overwrote config spec with previous version. These changes revert the config to the correct state.
=> fix(config): revert spec

src/index.ts, test/index.test.ts
Add jurisdictionCode param to getConsent
Update tests
> Description here
> Fix [#1]()
=> fix(getConsent): add jurisdictionCode param

src/index.ts
GetConsent purpose response value PurposeAllowed | string to support shoreline v1 and v2
=> fix(getConsent): optional allowed

src/index.ts
Update invoke right to use rightCode
Add canonicalPurpose metadata
Add vendor metadata
=> fix(invokeRight): rightCode + additional metadata

src/index.ts
Re add purpose canonicalPurposeCode for backwards compatibility
=> fix(config): purpose canonicalPurposeCode

src/index.ts
> adds enum entry for reject all
> manual/local with lanyard and figurehead changes
https://github.com/ketch-com/figurehead/pull/2212
https://github.com/ketch-com/lanyard/pull/477/files
> https://ketch-com.atlassian.net/browse/KD-4339
=> feat: reject all enum

src/index.ts
Add additional identity metadata
DSR data subject info
Handle data subject user input request
Consent priority
=> fix(interface): identity + data subject

src/index.ts
Handle switch color configs
Handle switch text
=> fix(config): switch text + color

.github/workflows/ci.yml, .npmignore, package-lock.json, package.json
Add npm login for publishing
N/A
=> fix: npm login

.github/workflows/ci.yml
=> fix: login

.github/workflows/ci.yml
=> fix: publish

src/index.ts
Move close icon config to logical place
Never switch text
Optional cookies
=> fix(config): close icon

src/index.ts
=> fix(theme): qr code

package-lock.json, package.json, src/fetch.ts, src/index.test.ts, src/index.ts
Refactor into a class
Refactor fetch testing
Add preferences QR
Add web report
Unit tests
=> refactor: turn API into a class and refactor fetch testing

package-lock.json, package.json, src/index.ts
=> fix: fetch

docs/classes/KetchWebAPI.html, package-lock.json, package.json
=> feat: add read repair to get consent

docs/classes/KetchWebAPI.html, package-lock.json, package.json, tsconfig.json
Import helpers to reduce bundle size
Unit tests
N/A
=> fix: import helpers

docs/classes/KetchWebAPI.html, jest.config.js, package-lock.json, package.json
=> chore: bump dependencies

.gitattributes, docs/classes/KetchWebAPI.html, package-lock.json, package.json, src/index.test.ts
Upgrade dependencies
Unit tests
=> chore: Upgrade dependencies

src/index.test.ts, src/index.ts
Handle synthetic responses
Unit tests
=> fix: synthetic responses

src/index.test.ts, src/index.ts
=> fix: swap org code check with purposes

src/index.test.ts, src/index.ts
> throw error in post so it propigates to callers
> https://ketch-com.atlassian.net/browse/KD-9142
=> feat: recaptcha on invoke right request

src/index.ts
This would be useful in web frameworks that don't have global fetch.
The tests pass. The change was also verified within a framework with it's own fetch being passed as `fetchOverride`.
=> chore: Add parameter to override fetch API

package-lock.json, package.json, src/index.test.ts, src/index.ts
API endpoint change to fetch subscriptions configuration
=> feat: property specific subscriptions

package-lock.json, package.json
=> chore: ketch types version bump

src/index.ts
Binds fetch to window object to resolve below issue
=> fix: bind fetch to window

package-lock.json, package.json, src/index.test.ts, src/index.ts
=> fix(config): add org

src/index.test.ts, src/index.ts
=> fix(config): route

src/index.test.ts, src/index.ts
=> fix(config): hash

src/index.ts
=> fix(config): pretty

package-lock.json, package.json, src/index.test.ts, src/index.ts
Include set consent response
Unit tests
=> fix(consent): set

package-lock.json, package.json
=> fix: type bump
